# frozen_string_literal: true

## THIS IS AN AUTOGENERATED FILE--DO NOT EDIT
module Rlox
  class Expr
  end

  class Binary < Expr
    attr_reader :left_expression
    attr_reader :operator_token
    attr_reader :right_expression

    def initialize(left_expression, operator_token, right_expression)
      @left_expression = left_expression 
      @operator_token = operator_token 
      @right_expression = right_expression 
    end
  end
  class Grouping < Expr
    attr_reader :expression

    def initialize(expression)
      @expression = expression 
    end
  end
  class Literal < Expr
    attr_reader :literal_value

    def initialize(literal_value)
      @literal_value = literal_value 
    end
  end
  class Unary < Expr
    attr_reader :operator_token
    attr_reader :right_expression

    def initialize(operator_token, right_expression)
      @operator_token = operator_token 
      @right_expression = right_expression 
    end
  end
end
